"""用例层端口(ADR-0030 阶段2):图节点与业务服务依赖的协作者契约。

Protocol 为结构化子类型——infrastructure 实现无需继承,经类型注解声明
意图;组装点(graph.runtime.build_engine)是唯一知道具体实现的地方。
"""

from __future__ import annotations

from typing import Any, Protocol


class EventBus(Protocol):
    """SSE 事件总线:按 story(thread)隔离的广播 + 历史。"""

    def emit(self, kind: str, data: dict, thread_id: str | None = None) -> None: ...
    def subscribe(self, thread_id: str): ...
    def unsubscribe(self, q) -> None: ...
    def has_subscribers(self, thread_id: str) -> bool: ...
    def snapshot(self, thread_id: str) -> list: ...
    def clear_events(self, thread_id: str) -> None: ...


class RunStateStore(Protocol):
    """运行状态持久化(ADR-0027):running/waiting/idle + 中断卡。"""

    def set_run_state(self, story_id: str, *, status: str,
                      run_id: str | None = None,
                      interrupt_type: str | None = None,
                      interrupt_payload: str | None = None,
                      error_code: str | None = None,
                      error_stage: str | None = None,
                      target_chapters: int | None = None) -> None: ...
    def get_run_state(self, story_id: str) -> dict | None: ...


class DirectiveChannel(Protocol):
    """用户指令通道:任意时刻输入,生成时消费(ADR-0024)。"""

    def record_directive(self, story_id: str, content: str) -> str: ...
    def peek_pending_directives(self, story_id: str) -> list[dict]: ...
    def mark_directives_consumed(self, directive_ids: list[str]) -> None: ...


class RecapBuilder(Protocol):
    """记忆拼装:短期衔接 + 分层剧情回顾 + 细纲解析(ADR-0003)。"""

    def recent_carryover(self, state: dict) -> str: ...
    def stage_chapter_summaries(self, story_id: str, stage_start: int, *,
                                upto: int) -> list[tuple[int, str]]: ...
    def story_recap(self, state: dict) -> str: ...
    def parse_stage_range(self, stage_outline: str, *, start: int) -> int: ...
    def extract_stage_line(self, stage_outline: str, chapter_no: int) -> str: ...


class StylePolicy(Protocol):
    """叙述风格策略:动态句式黑名单 + 规范名词典(ADR-0017/0019/0035)。"""

    def recent_phrase_blacklist(self, story_id: str, chapter_no: int, *,
                                exclude_texts: list[str] | None = None) -> list[str]: ...
    def canonical_entity_registry(self, story_id: str) -> list[dict]: ...


class CharacterRegistry(Protocol):
    """角色/实体簿记辅助:名字映射、共创种子落库、合并提案裁决(ADR-0015)。"""

    def character_name_map(self, state: dict) -> dict[str, str]: ...
    def prepare_character_seeds(self, state: dict) -> dict: ...
    def commit_character_seeds(self, plan: dict, *, commit: bool = True) -> list[str]: ...
    def resolve_entity_proposal(self, proposal_id: str, action: str) -> dict: ...


class FailureLedger(Protocol):
    """审计台账:评审记录 + LLM 失败留痕(评审 6.9/ADR-0026)。"""

    def log_review(self, state: dict, *, reviewer: str, verdict: dict,
                   round_no: int, forced: bool | None = None) -> None: ...
    def log_llm_failure(self, *, story_id: str, stage: str, node: str,
                        exc: Exception) -> None: ...


class FinalizeStore(Protocol):
    """定稿原子落库(ADR-0003 写链路):单事务,失败整体回滚。"""

    def commit_finalize(self, state: dict) -> str: ...


class StopController(Protocol):
    """协作式停止:置位/清除/检查(节点入口抛 StopRequested)。"""

    def request_stop(self, story_id: str) -> None: ...
    def clear_stop(self, story_id: str) -> None: ...
    def check_stop(self, story_id: str) -> None: ...
